import type { StateInfo } from '../types';

export const STATES: StateInfo[] = [
  { code: 'AL', name: 'Alabama',       fredCodes: { sthpi: 'ALSTHPI',  permits: 'ALBPPRIVSA',  daysOnMarket: 'MEDDAYONMARAL', existingSales: 'ALEHOSUSQ176N' } },
  { code: 'AK', name: 'Alaska',        fredCodes: { sthpi: 'AKSTHPI',  permits: 'AKBPPRIVSA',  daysOnMarket: 'MEDDAYONMARAK' } },
  { code: 'AZ', name: 'Arizona',       fredCodes: { sthpi: 'AZSTHPI',  permits: 'AZBPPRIVSA',  daysOnMarket: 'MEDDAYONMARAZ' } },
  { code: 'AR', name: 'Arkansas',      fredCodes: { sthpi: 'ARSTHPI',  permits: 'ARBPPRIVSA',  daysOnMarket: 'MEDDAYONMARAR' } },
  { code: 'CA', name: 'California',    fredCodes: { sthpi: 'CASTHPI',  permits: 'CABPPRIVSA',  daysOnMarket: 'MEDDAYONMARCA' } },
  { code: 'CO', name: 'Colorado',      fredCodes: { sthpi: 'COSTHPI',  permits: 'COBPPRIVSA',  daysOnMarket: 'MEDDAYONMARCO' } },
  { code: 'CT', name: 'Connecticut',   fredCodes: { sthpi: 'CTSTHPI',  permits: 'CTBPPRIVSA',  daysOnMarket: 'MEDDAYONMARCT' } },
  { code: 'DE', name: 'Delaware',      fredCodes: { sthpi: 'DESTHPI',  permits: 'DEBPPRIVSA',  daysOnMarket: 'MEDDAYONMARDE' } },
  { code: 'DC', name: 'Washington DC', fredCodes: { sthpi: 'DCSTHPI',  permits: 'DCBPPRIVSA',  daysOnMarket: 'MEDDAYONMARDC' } },
  { code: 'FL', name: 'Florida',       fredCodes: { sthpi: 'FLSTHPI',  permits: 'FLBPPRIVSA',  daysOnMarket: 'MEDDAYONMARFL' } },
  { code: 'GA', name: 'Georgia',       fredCodes: { sthpi: 'GASTHPI',  permits: 'GABPPRIVSA',  daysOnMarket: 'MEDDAYONMARGA' } },
  { code: 'HI', name: 'Hawaii',        fredCodes: { sthpi: 'HISTHPI',  permits: 'HIBPPRIVSA',  daysOnMarket: 'MEDDAYONMARHI' } },
  { code: 'ID', name: 'Idaho',         fredCodes: { sthpi: 'IDSTHPI',  permits: 'IDBPPRIVSA',  daysOnMarket: 'MEDDAYONMARID' } },
  { code: 'IL', name: 'Illinois',      fredCodes: { sthpi: 'ILSTHPI',  permits: 'ILBPPRIVSA',  daysOnMarket: 'MEDDAYONMARIL' } },
  { code: 'IN', name: 'Indiana',       fredCodes: { sthpi: 'INSTHPI',  permits: 'INBPPRIVSA',  daysOnMarket: 'MEDDAYONMARIN' } },
  { code: 'IA', name: 'Iowa',          fredCodes: { sthpi: 'IASTHPI',  permits: 'IABPPRIVSA',  daysOnMarket: 'MEDDAYONMARIA' } },
  { code: 'KS', name: 'Kansas',        fredCodes: { sthpi: 'KSSTHPI',  permits: 'KSBPPRIVSA',  daysOnMarket: 'MEDDAYONMARKS' } },
  { code: 'KY', name: 'Kentucky',      fredCodes: { sthpi: 'KYSTHPI',  permits: 'KYBPPRIVSA',  daysOnMarket: 'MEDDAYONMARKY' } },
  { code: 'LA', name: 'Louisiana',     fredCodes: { sthpi: 'LASTHPI',  permits: 'LABPPRIVSA',  daysOnMarket: 'MEDDAYONMARLA' } },
  { code: 'ME', name: 'Maine',         fredCodes: { sthpi: 'MESTHPI',  permits: 'MEBPPRIVSA',  daysOnMarket: 'MEDDAYONMARME' } },
  { code: 'MD', name: 'Maryland',      fredCodes: { sthpi: 'MDSTHPI',  permits: 'MDBPPRIVSA',  daysOnMarket: 'MEDDAYONMARMD' } },
  { code: 'MA', name: 'Massachusetts', fredCodes: { sthpi: 'MASTHPI',  permits: 'MABPPRIVSA',  daysOnMarket: 'MEDDAYONMARMA' } },
  { code: 'MI', name: 'Michigan',      fredCodes: { sthpi: 'MISTHPI',  permits: 'MIBPPRIVSA',  daysOnMarket: 'MEDDAYONMARMI' } },
  { code: 'MN', name: 'Minnesota',     fredCodes: { sthpi: 'MNSTHPI',  permits: 'MNBPPRIVSA',  daysOnMarket: 'MEDDAYONMARMN' } },
  { code: 'MS', name: 'Mississippi',   fredCodes: { sthpi: 'MSSTHPI',  permits: 'MSBPPRIVSA',  daysOnMarket: 'MEDDAYONMARMS' } },
  { code: 'MO', name: 'Missouri',      fredCodes: { sthpi: 'MOSTHPI',  permits: 'MOBPPRIVSA',  daysOnMarket: 'MEDDAYONMARMO' } },
  { code: 'MT', name: 'Montana',       fredCodes: { sthpi: 'MTSTHPI',  permits: 'MTBPPRIVSA',  daysOnMarket: 'MEDDAYONMARMT' } },
  { code: 'NE', name: 'Nebraska',      fredCodes: { sthpi: 'NESTHPI',  permits: 'NEBPPRIVSA',  daysOnMarket: 'MEDDAYONMARNE' } },
  { code: 'NV', name: 'Nevada',        fredCodes: { sthpi: 'NVSTHPI',  permits: 'NVBPPRIVSA',  daysOnMarket: 'MEDDAYONMARNV' } },
  { code: 'NH', name: 'New Hampshire', fredCodes: { sthpi: 'NHSTHPI',  permits: 'NHBPPRIVSA',  daysOnMarket: 'MEDDAYONMARNH' } },
  { code: 'NJ', name: 'New Jersey',    fredCodes: { sthpi: 'NJSTHPI',  permits: 'NJBPPRIVSA',  daysOnMarket: 'MEDDAYONMARNJ' } },
  { code: 'NM', name: 'New Mexico',    fredCodes: { sthpi: 'NMSTHPI',  permits: 'NMBPPRIVSA',  daysOnMarket: 'MEDDAYONMARNM' } },
  { code: 'NY', name: 'New York',      fredCodes: { sthpi: 'NYSTHPI',  permits: 'NYBPPRIVSA',  daysOnMarket: 'MEDDAYONMARNY' } },
  { code: 'NC', name: 'North Carolina',fredCodes: { sthpi: 'NCSTHPI',  permits: 'NCBPPRIVSA',  daysOnMarket: 'MEDDAYONMARNC' } },
  { code: 'ND', name: 'North Dakota',  fredCodes: { sthpi: 'NDSTHPI',  permits: 'NDBPPRIVSA',  daysOnMarket: 'MEDDAYONMARND' } },
  { code: 'OH', name: 'Ohio',          fredCodes: { sthpi: 'OHSTHPI',  permits: 'OHBPPRIVSA',  daysOnMarket: 'MEDDAYONMAROH' } },
  { code: 'OK', name: 'Oklahoma',      fredCodes: { sthpi: 'OKSTHPI',  permits: 'OKBPPRIVSA',  daysOnMarket: 'MEDDAYONMAROK' } },
  { code: 'OR', name: 'Oregon',        fredCodes: { sthpi: 'ORSTHPI',  permits: 'ORBPPRIVSA',  daysOnMarket: 'MEDDAYONMAROR' } },
  { code: 'PA', name: 'Pennsylvania',  fredCodes: { sthpi: 'PASTHPI',  permits: 'PABPPRIVSA',  daysOnMarket: 'MEDDAYONMARPA' } },
  { code: 'RI', name: 'Rhode Island',  fredCodes: { sthpi: 'RISTHPI',  permits: 'RIBPPRIVSA',  daysOnMarket: 'MEDDAYONMARRI' } },
  { code: 'SC', name: 'South Carolina',fredCodes: { sthpi: 'SCSTHPI',  permits: 'SCBPPRIVSA',  daysOnMarket: 'MEDDAYONMARSC' } },
  { code: 'SD', name: 'South Dakota',  fredCodes: { sthpi: 'SDSTHPI',  permits: 'SDBPPRIVSA',  daysOnMarket: 'MEDDAYONMARSD' } },
  { code: 'TN', name: 'Tennessee',     fredCodes: { sthpi: 'TNSTHPI',  permits: 'TNBPPRIVSA',  daysOnMarket: 'MEDDAYONMARTN' } },
  { code: 'TX', name: 'Texas',         fredCodes: { sthpi: 'TXSTHPI',  permits: 'TXBPPRIVSA',  daysOnMarket: 'MEDDAYONMARTX' } },
  { code: 'UT', name: 'Utah',          fredCodes: { sthpi: 'UTSTHPI',  permits: 'UTBPPRIVSA',  daysOnMarket: 'MEDDAYONMARUT' } },
  { code: 'VT', name: 'Vermont',       fredCodes: { sthpi: 'VTSTHPI',  permits: 'VTBPPRIVSA',  daysOnMarket: 'MEDDAYONMARVT' } },
  { code: 'VA', name: 'Virginia',      fredCodes: { sthpi: 'VASTHPI',  permits: 'VABPPRIVSA',  daysOnMarket: 'MEDDAYONMARVA' } },
  { code: 'WA', name: 'Washington',    fredCodes: { sthpi: 'WASTHPI',  permits: 'WABPPRIVSA',  daysOnMarket: 'MEDDAYONMARWA' } },
  { code: 'WV', name: 'West Virginia', fredCodes: { sthpi: 'WVSTHPI',  permits: 'WVBPPRIVSA',  daysOnMarket: 'MEDDAYONMARWV' } },
  { code: 'WI', name: 'Wisconsin',     fredCodes: { sthpi: 'WISTHPI',  permits: 'WIBPPRIVSA',  daysOnMarket: 'MEDDAYONMARWI' } },
  { code: 'WY', name: 'Wyoming',       fredCodes: { sthpi: 'WYSTHPI',  permits: 'WYBPPRIVSA',  daysOnMarket: 'MEDDAYONMARWY' } },
];

export function getStateByCode(code: string): StateInfo | undefined {
  return STATES.find(s => s.code === code);
}
